### ISSUE TITLE
Password Reset Api

### ISSUE THREAD

**Issue by executive-chef** [ucladevx/bruincreates-backend#1]
## User Story
As the user, I want to place an order on the website.

## Detailed Description
User clicks password reset button, a reset url is sent to user's email address. Frontend application sends another reset request with jwt token, the server validates the token and update user profile.

## Acceptance Criteria
- [x] Design
- [x] Api for sending email reset url
- [x] Api for updating user password

**Comment by tonydd02** [comment]
Completed : )
