### ISSUE TITLE
Cancel Order

### ISSUE THREAD

**Issue by executive-chef** [ucladevx/bruincreates-backend#6]
## User Story
As an user, I would like to cancel the order I placed so that I can change my mind.

## Detailed Description
Given a cancel order request, the server first check if the caller is the buyer and if the order has not been shipped. If so, a deletion is made by mark the order as deleted. (no physical delete).

## Acceptance Criteria
- [x] #10

**Comment by NicholasPDean** [comment]
Done with 6f0ec99

@aojiaooo

**Comment by executive-chef** [comment]
Confirmed
